INSERT INTO CLASSROOM (TRAINERNAME ) VALUES ('Testerino');
INSERT INTO CLASSROOM (TRAINERNAME ) VALUES ('Matt');
INSERT INTO TRAINEE (TRAINEENAME, CLASSROOM_ID) VALUES ('Tester', 1);
INSERT INTO TRAINEE (TRAINEENAME, CLASSROOM_ID) VALUES ('Ger', 1);
INSERT INTO TRAINEE (TRAINEENAME, CLASSROOM_ID) VALUES ('Vince', 1);
INSERT INTO TRAINEE (TRAINEENAME, CLASSROOM_ID) VALUES ('July', 2);
INSERT INTO TRAINEE (TRAINEENAME, CLASSROOM_ID) VALUES ('Aoife', 2);
INSERT INTO TRAINEE (TRAINEENAME, CLASSROOM_ID) VALUES ('Fiona', 2);